spring:
  profiles:
    active: dev
    include: secret
  jpa:
    hibernate:
#      ddl-auto: create-drop
                  ddl-auto: update
    jdbc:
      batch_size=50
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  main:
    allow-bean-definition-overriding: true
  exe-path: ${EXE_PATH}
  exe-directory: ${EXE_DIRECTORY}
  ino-file-name: ${INO_FILE_NAME}

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB